### ISSUE TITLE
V4.0.2-RC1: NFE at clanChest.clanChestCrownsPercent when parsing from json

### ISSUE THREAD

**Issue by mlieshoff** [mlieshoff/jcrapi#1]
```
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 0.186 at line 1 column 499 path $.clanChest.clanChestCrownsPercent
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:227)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:217)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
	at com.google.gson.Gson.fromJson(Gson.java:773)
	at jcrapi.Client.getClan(Client.java:77)
	at jcrapi.Api.getClan(Api.java:81)
	at rcf.db2.Update.start(Update.java:28)
	at rcf.db2.Update.main(Update.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.NumberFormatException: Expected an int but was 0.186 at line 1 column 499 path $.clanChest.clanChestCrownsPercent
	at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1204)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:225)
	... 18 more
```

**Comment by mlieshoff** [comment]
fixed in https://bintray.com/mlieshoff/maven/jcrapi/4.0.2-RC1.1
