### ISSUE TITLE
type of clanChestCrownsPercent atribute

### ISSUE THREAD

**Issue by edermfl** [mlieshoff/jcrapi#2]
Exists a modeling wrong for clanChestCrownsPercent atribute at ClanChest class.
During the chest crowns the percent can by decimal, this case the api throws:
com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 49.94 at line 1 column 492 path $.clanChest.clanChestCrownsPercent
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:245) ~[gson-2.8.0.jar:na]
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:235) ~[gson-2.8.0.jar:na]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[gson-2.8.0.jar:na]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[gson-2.8.0.jar:na]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[gson-2.8.0.jar:na]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[gson-2.8.0.jar:na]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:na]
        at com.google.gson.Gson.fromJson(Gson.java:852) ~[gson-2.8.0.jar:na]
        at com.google.gson.Gson.fromJson(Gson.java:801) ~[gson-2.8.0.jar:na]
        at com.google.gson.Gson.fromJson(Gson.java:773) ~[gson-2.8.0.jar:na]
        at jcrapi.Client.getClan(Client.java:77) ~[jcrapi-4.0.2-RC1.jar:na]
        at jcrapi.Api.getClan(Api.java:81) ~[jcrapi-4.0.2-RC1.jar:na]

**Comment by mlieshoff** [comment]
Hi Eder

it's fixed in https://bintray.com/mlieshoff/maven/jcrapi/4.0.2-RC1.1

Best Regards

**Comment by edermfl** [comment]
Hi Michael,
Files not found in  repository: https://bintray.com/mlieshoff/maven/jcrapi/4.0.2-RC1.1#files/jcrapi/jcrapi
Can you verify?
[]'s

**Comment by mlieshoff** [comment]
Hi Eder, please try again.
