### ISSUE TITLE
Clan Search with spaces returns ConnectionClosedException

### ISSUE THREAD

**Issue by ZeNeLLiE** [mlieshoff/jcrapi#34]
Clan search with spaces gets exception most of the time (probably 90%). Occasionally it works though.

```
 // all set values are optional
		ClanSearch clanSearch = new ClanSearch();
		clanSearch.setName("reddit%20alpha");
		clanSearch.setScore(500);
		clanSearch.setMinMembers(10);
		clanSearch.setMaxMembers(25);
		System.out.println("Searching clan name: "+clanSearch.getName());
		List<Clan> clansWithCriteria = api.getClanSearch(clanSearch);
		System.out.println("Clans found: "+clansWithCriteria.size());
```

Output:

> Searching clan name: reddit%20alpha
Exception in thread "main" jcrapi.ApiException: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 489252; received: 87349
	at jcrapi.Api.getClanSearch(Api.java:136)
	at jcrapi.Main.main(Main.java:23)
Caused by: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 489252; received: 87349
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:180)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at jcrapi.Crawler.get(Crawler.java:56)
	at jcrapi.Client.getClanSearch(Client.java:133)
	at jcrapi.Api.getClanSearch(Api.java:134)
	... 1 more

Other parameters used:
**Searching clan name: reddit**
Clans found: 53

**Searching clan name: reddit+alpha**
Exception in thread "main" jcrapi.ApiException: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 489258; received: 87349
	at jcrapi.Api.getClanSearch(Api.java:136)
	at jcrapi.Main.main(Main.java:23)
Caused by: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 489258; received: 87349
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:180)

**(Another issue, wrapper should handle and do url encoding)**
**Searching clan name: reddit alpha** 
Exception in thread "main" java.lang.IllegalArgumentException: Illegal character in query at index 45: http://api.cr-api.com/clan/search?name=reddit alpha&score=500&minMembers=10&maxMembers=25
	at java.net.URI.create(URI.java:852)
	at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:69)
	at jcrapi.Crawler.createRequest(Crawler.java:63)
	at jcrapi.Crawler.get(Crawler.java:47)
	at jcrapi.Client.getClanSearch(Client.java:133)
	at jcrapi.Api.getClanSearch(Api.java:134)
	at jcrapi.Main.main(Main.java:23)

**Comment by mlieshoff** [comment]
Thank you, nice catch! And very cool issue description.

**Comment by mlieshoff** [comment]
Agree that wrapper should do encoding, but input parameters should be not encoded. Will be fixed in next version of wrapper.

**Comment by mlieshoff** [comment]
@ZeNeLLiE  issue fixed in v8.4.53-RC1

**Comment by ZeNeLLiE** [comment]
Thanks!

**Comment by ZeNeLLiE** [comment]
Hi @mlieshoff 
Still I am getting premature end of content-length error when i search for "reddit alpha"

> Searching clan name: reddit alpha
Exception in thread "main" jcrapi.ApiException: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 489197; received: 87349
	at jcrapi.Api.getClanSearch(Api.java:136)
	at jcrapi.Main.main(Main.java:23)
Caused by: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 489197; received: 87349
